### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "john@example.com",
  "password": "johny"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=alex@example.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/22

### Update a user with a given id
PATCH http://localhost:3000/auth/13
content-type: application/json

{
  "password": "alex"
}
